version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          yarn: true
      - cypress/run:
          requires:
            - cypress/install
          yarn: true
          record: true
          parallel: true
          parallelism: 4
          group: 'all tests'
          command: 'yarn run test:e2e'
